apiVersion: v1
kind: Service
metadata:
  name: simple-service
spec:
  selector:   # Label Selector = 
    app: simple
  ports:
    - protocol: TCP
      port: 80 # Service Port
      targetPort: 80 # Container Port

# By default, Service type is ClusterIP